namespace Beatmap.Enums
{
    public enum EaseType
    {
        None = -1,
        Linear,
        InQuadratic,
        OutQuadratic,
        InOutQuadratic,
        InSinusoidal,
        OutSinusoidal,
        InOutSinusoidal,
        InCubic,
        OutCubic,
        InOutCubic,
        InQuartic,
        OutQuartic,
        InOutQuartic,
        InQuintic,
        OutQuintic,
        InOutQuintic,
        InExponential,
        OutExponential,
        InOutExponential,
        InCircular,
        OutCircular,
        InOutCircular,
        InBack,
        OutBack,
        InOutBack,
        InElastic,
        OutElastic,
        InOutElastic,
        InBounce,
        OutBounce,
        InOutBounce,
        BeatSaberInOutBack = 100,
        BeatSaberInOutElastic,
        BeatSaberInOutBounce
    }
}
